### ISSUE TITLE
[Feature Request] Custom background transparency

### ISSUE THREAD

**Issue by YunYouJun** [klauscfhq/hyper-pokemon#53]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want a translucent effect like iTerm.
How about adding a configuration to custom opacity?

**Additional context**

![image](https://user-images.githubusercontent.com/25154432/74755955-dafca900-52ae-11ea-9028-c0d167ecabbc.png)
![image](https://user-images.githubusercontent.com/25154432/74756030-f071d300-52ae-11ea-921e-25e5f809f65e.png)

**Comment by YunYouJun** [comment]
Maybe we just need add opacity property for here?
```css 4
.terms_terms {
  background: url("file://${imagePath}") center;
  background-size: cover;
  opacity: ${opacity}
}
```

https://github.com/klaussinani/hyper-pokemon/blob/98abad0879922743d07c0f2c6f97d9c0aa04f5c3/index.js#L128
